# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([], blank=True, null=True)),
                ('body_en', wagtail.core.fields.StreamField([], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Warning: This title is also the exact classname used to reference the icon in the CSS.', max_length=255)),
                ('unicode_value', models.CharField(default='', help_text='Warning: This unicode value is how the icon is referenced in the font file.', max_length=255)),
                ('category', models.CharField(choices=[('1', 'Database'), ('2', 'Zodiacs'), ('3', 'Windows'), ('4', 'Weather'), ('5', 'Video'), ('6', 'User Interface'), ('7', 'Transportation'), ('8', 'Touch Gestures'), ('9', 'Time'), ('10', 'Text'), ('11', 'Sports'), ('12', 'Speech Bubbles'), ('13', 'Social Media'), ('14', 'Signs/Symbols'), ('15', 'Shopping/E-commerce'), ('16', 'SEO Icons'), ('17', 'Security'), ('18', 'Science/Medical'), ('19', 'Photos'), ('20', 'People'), ('21', 'Nature'), ('22', 'Objects'), ('23', 'Music'), ('24', 'Media Control'), ('25', 'Maps/Locations'), ('26', 'Logos'), ('27', 'Interface'), ('28', 'Industry'), ('29', 'Hipster Style'), ('30', 'Hardware'), ('31', 'Halloween'), ('32', 'Food/Drinks'), ('33', 'Folders'), ('34', 'Flags'), ('35', 'Files'), ('36', 'Emoticons'), ('37', 'Emails'), ('38', 'Education'), ('39', 'Desktop Apps'), ('40', 'Design'), ('41', 'Communications/Network'), ('42', 'Clothes/Accessories'), ('43', 'Cloud'), ('44', 'Chess'), ('45', 'Christmas'), ('46', 'Buildings/Landmarks'), ('47', 'Business/Finance'), ('48', 'Body Parts'), ('49', 'Browsers/Operating Systems'), ('50', 'Arrow View'), ('51', 'Arrows'), ('52', 'Alignment'), ('53', 'Animals'), ('54', 'Doctor'), ('55', 'Places')], default='', max_length=3)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
