# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 21:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category display name', max_length=255)),
                ('slug', models.SlugField(help_text='Lowercase alphanumberic version of the display name used in URLs', max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('defaultpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.DefaultPage')),
                ('pagination', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, help_text='Choose how many posts appear per page')),
            ],
            options={
                'verbose_name_plural': 'Blog Index Pages',
                'verbose_name': 'Blog Index Page',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'app.defaultpage'),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('defaultpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.DefaultPage')),
                ('date', models.DateTimeField(default=datetime.datetime.today, help_text='Date displayed to the public, not related to scheduled publishing dates')),
                ('video_source', models.CharField(blank=True, choices=[('', 'None'), ('https://www.youtube.com/embed/', 'YouTube'), ('https://player.vimeo.com/video/', 'Vimeo')], default='', help_text='The source of the hosted header video', max_length=50, null=True, verbose_name='Header Video Source')),
                ('video_id', models.CharField(blank=True, help_text='The unique id from the selected source above. Should only consist of alphanumeric characters. Ex: 86036070', max_length=50, null=True, verbose_name='Header Video ID')),
                ('excerpt', models.CharField(blank=True, help_text='A teaser description of the content limited to 1000 characters', max_length=1000)),
                ('content', wagtail.core.fields.RichTextField()),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Manage categories using the <a href="/admin/snippets/app/blogcategory/">Snippets &raquo; Categories</a> option in the sidebar', to='app.BlogCategory')),
                ('image', models.ForeignKey(help_text='Header image also used as thumbnail', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.defaultpage',),
        ),
        migrations.RemoveField(
            model_name='defaultpage',
            name='body_en',
        ),
    ]
