# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-23 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181222_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorpages',
            name='body_500',
        ),
        migrations.RemoveField(
            model_name='errorpages',
            name='title_500',
        ),
    ]
