# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-01 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('app', '0006_auto_20190216_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation_type', models.CharField(blank=True, choices=[('standard-bar.html', 'Standard Bar'), ('centered-bar.html', 'Centered Bar'), ('app-bar.html', 'App Bar'), ('full-screen.html', 'Full Screen'), ('side-bar.html', 'Side Bar'), ('no-nav.html', 'No Nav')], default='', help_text='Choose a navigation style', max_length=50, null=True, verbose_name='Navigation Type')),
                ('footer_type', models.CharField(blank=True, choices=[('long-1.html', 'Long 1'), ('long-2.html', 'Long 2'), ('short-1.html', 'Short 1'), ('short-2.html', 'Short 2'), ('short-3.html', 'Short 3'), ('short-4.html', 'Short 4'), ('short-5.html', 'Short 5'), ('subscribe.html', 'Subscribe'), ('no-footer.html', 'No Footer')], default='', help_text='Choose a footer style', max_length=50, null=True, verbose_name='Footer Type')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
