# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-01 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sitesettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSettings',
            new_name='HeaderFooter',
        ),
        migrations.AlterModelOptions(
            name='headerfooter',
            options={'verbose_name': 'Header & Footer'},
        ),
    ]
