# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-01 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('app', '0008_auto_20190301_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='footer_logo',
            field=models.ForeignKey(blank=True, help_text='Logo used in header. Recommended transparent PNG', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_logo', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='header_logo',
            field=models.ForeignKey(blank=True, help_text='Logo used in header. Recommended transparent PNG', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_logo', to='wagtailimages.Image'),
        ),
    ]
