# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-01 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190301_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='social_facebook',
            field=models.CharField(blank=True, default='', help_text='Enter your Facebook link here.', max_length=250, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='social_instagram',
            field=models.CharField(blank=True, default='', help_text='Enter your Instagram link here.', max_length=250, null=True, verbose_name='Instagram Link'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='social_linkedin',
            field=models.CharField(blank=True, default='', help_text='Enter your LinkedIn link here.', max_length=250, null=True, verbose_name='LinkedIn Link'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='social_twitter',
            field=models.CharField(blank=True, default='', help_text='Enter your Twitter link here.', max_length=250, null=True, verbose_name='Twitter Link'),
        ),
    ]
