# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-01 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190301_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='copyright_text',
            field=models.CharField(blank=True, default='', help_text='Enter the text that should appear after the year in the copyright line.', max_length=250, null=True, verbose_name='Copyright text'),
        ),
    ]
