# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-01 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_headerfooter_copyright_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerfooter',
            name='footer_type',
            field=models.CharField(choices=[('no-footer.html', 'No Footer'), ('long-1.html', 'Long 1'), ('long-2.html', 'Long 2'), ('short-1.html', 'Short 1'), ('short-2.html', 'Short 2'), ('short-3.html', 'Short 3'), ('short-4.html', 'Short 4'), ('short-5.html', 'Short 5'), ('subscribe.html', 'Subscribe')], default='no-footer.html', help_text='Choose a footer style', max_length=50, verbose_name='Footer Type'),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='navigation_type',
            field=models.CharField(choices=[('no-nav.html', 'No Nav'), ('standard-bar.html', 'Standard Bar'), ('centered-bar.html', 'Centered Bar'), ('app-bar.html', 'App Bar'), ('full-screen.html', 'Full Screen'), ('side-bar.html', 'Side Bar')], default='no-nav.html', help_text='Choose a navigation style', max_length=50, verbose_name='Navigation Type'),
        ),
    ]
