# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-02 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190302_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='header_automatic_nav',
            field=models.BooleanField(default=True, help_text='Automatically populate the nav with top-level menu pages', verbose_name='Automatic Nav'),
        ),
    ]
