# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-02 06:42
from __future__ import unicode_literals

import app.blocks.custom_choice_block
import app.widgets.custom_radio_select
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_headerfooter_header_automatic_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Enter the text that should appear in the tag line.', max_length=250, null=True, verbose_name='Tagline text'),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='header_links',
            field=wagtail.core.fields.StreamField([('header_link_block', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.StructBlock([('link_type', app.blocks.custom_choice_block.CustomChoiceBlock(choices=(('url', 'URL'), ('page', 'Page'), ('document', 'Document'), ('email', 'Email')), default='url', label='Type', required=False, widget=app.widgets.custom_radio_select.CustomRadioSelect)), ('url', wagtail.core.blocks.CharBlock(label='URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('email', wagtail.core.blocks.EmailBlock(required=False)), ('phone', wagtail.core.blocks.CharBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Text', required=False)), ('children', wagtail.core.blocks.StreamBlock([('link', wagtail.core.blocks.StructBlock([('link_type', app.blocks.custom_choice_block.CustomChoiceBlock(choices=(('url', 'URL'), ('page', 'Page'), ('document', 'Document'), ('email', 'Email')), default='url', label='Type', required=False, widget=app.widgets.custom_radio_select.CustomRadioSelect)), ('url', wagtail.core.blocks.CharBlock(label='URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('email', wagtail.core.blocks.EmailBlock(required=False)), ('phone', wagtail.core.blocks.CharBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Text', required=False))]))], blank=True, null=True, required=False))]))]))], blank=True, help_text='Populate the nav with custom links', null=True, verbose_name='Links'),
        ),
    ]
