# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-08 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('app', '0015_auto_20190302_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='header_banner_image',
            field=models.ForeignKey(blank=True, help_text='Banner Image', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_banner_image', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='header_banner_text_1',
            field=models.CharField(blank=True, default='', help_text='Enter one line of text', max_length=250, null=True, verbose_name='Banner Text Line 1'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='header_banner_text_2',
            field=models.CharField(blank=True, default='', help_text='Enter one line of text', max_length=250, null=True, verbose_name='Banner Text Line 2'),
        ),
    ]
