# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-08 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190308_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerfooter',
            name='header_banner_image',
        ),
    ]
