# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-26 16:39
from __future__ import unicode_literals

import app.blocks.custom_choice_block
import app.widgets.custom_radio_select
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_headerfooter_footer_category_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerfooter',
            name='footer_category_links',
            field=wagtail.core.fields.StreamField([('footer_category_link_block', wagtail.core.blocks.StructBlock([('category_label', wagtail.core.blocks.CharBlock(label='Category Name', required=False)), ('links', wagtail.core.blocks.StreamBlock([('link', wagtail.core.blocks.StructBlock([('link_type', app.blocks.custom_choice_block.CustomChoiceBlock(choices=(('', 'None'), ('url', 'URL'), ('page', 'Page'), ('document', 'Document'), ('email', 'Email'), ('phone', 'Phone')), default='', label='Type', required=False, widget=app.widgets.custom_radio_select.CustomRadioSelect)), ('url', wagtail.core.blocks.CharBlock(label='URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('email', wagtail.core.blocks.EmailBlock(required=False)), ('phone', wagtail.core.blocks.CharBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Text', required=False)), ('link_format', app.blocks.custom_choice_block.CustomChoiceBlock(choices=(('', 'Text'), ('btn btn--primary', 'Button')), default='', label='Format', required=False, widget=app.widgets.custom_radio_select.CustomRadioSelect))]))], label='link', required=True))]))], blank=True, help_text='Populate the footer with categorized links', null=True, verbose_name='Categorized Links'),
        ),
    ]
