# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190514_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='social_youtube',
            field=models.CharField(blank=True, default='', help_text='Enter your YouTube link here.', max_length=250, null=True, verbose_name='YouTube Link'),
        ),
    ]
