# Generated by Django 3.0.4 on 2020-03-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_datetime']},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.TextField(default=''),
        ),
    ]
