# Generated by Django 3.0.4 on 2020-03-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200318_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('benefits_meeting', 'Benefits Meeting'), ('benefits_training', 'Benefits Training'), ('webcast', 'Compliance Webcast'), ('tradeshow', 'Tradeshow')], default='', max_length=24),
        ),
    ]
