# Generated by Django 3.0.4 on 2020-03-18 21:14

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200318_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
    ]
