# Generated by Django 3.0.4 on 2020-03-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20200318_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address_city',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address_state',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address_zipcode',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
