# Generated by Django 3.0.4 on 2020-03-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200318_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ErrorPages',
        ),
    ]
