# Generated by Django 3.0.4 on 2020-03-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20200318_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL Name'),
        ),
    ]
