# Generated by Django 3.0.4 on 2020-03-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_event_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('defaultpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.DefaultPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.defaultpage',),
        ),
    ]
