# Generated by Django 3.0.4 on 2020-03-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20200325_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headerfooter',
            old_name='utility_nav',
            new_name='utility_links',
        ),
    ]
