# Generated by Django 3.0.4 on 2020-03-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20200325_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='utility_text',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Utility Text'),
        ),
    ]
