# Generated by Django 3.0.4 on 2020-03-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20200325_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='utility_background_color',
            field=models.CharField(choices=[('bg--light', 'Light'), ('bg--primary', 'Primary'), ('bg--secondary', 'Secondary'), ('bg--dark', 'Dark')], default='bg--light', max_length=50),
        ),
    ]
