# Generated by Django 3.0.4 on 2020-03-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_headerfooter_utility_background_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
