# Generated by Django 3.0.4 on 2020-03-26 04:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_remove_event_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('defaultpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.DefaultPage')),
                ('event_type', models.CharField(choices=[('Benefits Meeting', 'Benefits Meeting'), ('Benefits Training', 'Benefits Training'), ('Compliance Webcast', 'Compliance Webcast'), ('Tradeshow', 'Tradeshow')], default='', max_length=24, verbose_name='Event Type')),
                ('description', wagtail.core.fields.RichTextField(default='', verbose_name='Description')),
                ('location_type', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], default='', help_text='If online, no address is necessary', max_length=24, verbose_name='Location Type')),
                ('address_line_1', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Address Line 2')),
                ('address_city', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='City')),
                ('address_state', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='State')),
                ('address_zipcode', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Postal Code')),
                ('start_datetime', models.DateTimeField(help_text='The date and time the event starts.', verbose_name='Date & Time')),
                ('duration', models.DecimalField(blank=True, decimal_places=2, default=1, help_text='In hours', max_digits=4, null=True, verbose_name='Duration')),
                ('cost', models.CharField(default='Free', help_text='If adding a price, please use the currency symbol, e.g. $, £, etc.', max_length=50)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_datetime'],
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'app.defaultpage'),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='Last Name')),
                ('company', models.CharField(default='', max_length=255, verbose_name='Company')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='', max_length=16, verbose_name='Phone')),
                ('address1', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='State')),
                ('postalcode', models.CharField(default='', max_length=16, verbose_name='Postal Code')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_event', to='app.EventPage')),
            ],
        ),
    ]
