# Generated by Django 3.0.4 on 2020-03-26 18:54

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_eventpage_eventregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_header', models.CharField(max_length=255, verbose_name='Title')),
                ('notification_starttime', models.DateTimeField(help_text='The date and time of the start of notification.', verbose_name='Date & Time')),
                ('notification_endtime', models.DateTimeField(help_text='The date and time of the end of notification.', verbose_name='Date & Time')),
                ('notification_body', wagtail.core.fields.RichTextField(default='', verbose_name='Body')),
            ],
            options={
                'ordering': ['notification_starttime'],
            },
        ),
    ]
