# Generated by Django 3.0.4 on 2020-03-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_endtime',
            field=models.DateTimeField(help_text='The date and time of the end of notification.', verbose_name='Unpublished Date'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_starttime',
            field=models.DateTimeField(help_text='The date and time of the start of notification.', verbose_name='Published Date'),
        ),
    ]
