# Generated by Django 3.0.4 on 2020-03-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20200326_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['starttime']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_endtime',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_header',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_starttime',
            new_name='starttime',
        ),
        migrations.AddField(
            model_name='notification',
            name='location',
            field=models.CharField(choices=[('pos-top pos-left', 'Top Left'), ('pos-top pos-right', 'Top Right'), ('pos-bottom pos-left', 'Bottom Left'), ('pos-bottom pos-right', 'Bottom Right')], default='pos-top pos-left', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='size',
            field=models.CharField(choices=[('col-md-3', 'Extra Small'), ('col-md-4', 'Small'), ('col-md-6', 'Med'), ('col-md-12', 'Large')], default='col-md-3', max_length=50),
        ),
    ]
