# Generated by Django 3.0.4 on 2020-03-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20200326_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text_alignment',
            field=models.CharField(blank=True, choices=[('', 'Align Left'), ('text-center', 'Align Center'), ('text-right', 'Align Right')], default='', max_length=50, null=True),
        ),
    ]
