# Generated by Django 3.0.4 on 2020-03-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20200326_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='background_color',
            field=models.CharField(choices=[('bg--white', 'Light'), ('bg--primary', 'Primary'), ('bg--secondary', 'Secondary'), ('bg--dark', 'Dark')], default='bg--white', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text_alignment',
            field=models.CharField(blank=True, choices=[(' ', 'Align Left'), ('text-center', 'Align Center'), ('text-right', 'Align Right')], default=' ', max_length=50, null=True),
        ),
    ]
