# Generated by Django 3.0.4 on 2020-03-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_auto_20200327_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
