# Generated by Django 3.0.4 on 2020-03-26 23:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20200326_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('defaultpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.DefaultPage')),
                ('news_datetime', models.DateTimeField(help_text='The date and time of the press release.', verbose_name='Date & Time')),
            ],
            options={
                'verbose_name': 'Press Release',
                'verbose_name_plural': 'Press Releases',
                'ordering': ['news_datetime'],
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'app.defaultpage'),
        ),
        migrations.AlterModelOptions(
            name='newsindexpage',
            options={'verbose_name': 'News Index Page', 'verbose_name_plural': 'News Index Pages'},
        ),
    ]
