# Generated by Django 3.0.5 on 2020-04-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20200409_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpage',
            name='hide_in_sitemap',
            field=models.BooleanField(default=False, help_text="Don't show this page in the sitemap.", verbose_name='Hide in sitemap'),
        ),
    ]
