# Generated by Django 3.0.5 on 2020-04-13 20:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20200410_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationIndexPage',
            fields=[
                ('defaultpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.DefaultPage')),
            ],
            options={
                'verbose_name': 'Location Index Page',
                'verbose_name_plural': 'Location Index Pages',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'app.defaultpage'),
        ),
    ]
