# Generated by Django 3.0.5 on 2020-04-14 21:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('app', '0075_locationindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_photo', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
