# Generated by Django 3.0.5 on 2020-05-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_auto_20200424_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_location', to='app.Location'),
        ),
    ]
