# Generated by Django 3.0.5 on 2020-05-06 20:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_auto_20200504_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierIndexPage',
            fields=[
                ('defaultpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.DefaultPage')),
            ],
            options={
                'verbose_name': 'Carrier Index Page',
                'verbose_name_plural': 'Carrier Index Pages',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'app.defaultpage'),
        ),
    ]
