# Generated by Django 3.0.5 on 2020-05-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_auto_20200508_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='featured_event_bg_invert',
            field=models.CharField(choices=[('', 'icon-fa-times'), ('image--light', 'icon-fa-check')], default='', help_text='Invert the image overlay', max_length=50, verbose_name='Invert Dark/Light'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='featured_event_bg_overlay',
            field=models.CharField(choices=[('0', 'Off'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', 'Full')], default='0', help_text='Adjust the opacity of the background image overlay', max_length=50, verbose_name='Overlay Opacity'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='featured_news_bg_invert',
            field=models.CharField(choices=[('', 'icon-fa-times'), ('image--light', 'icon-fa-check')], default='', help_text='Invert the image overlay', max_length=50, verbose_name='Invert Dark/Light'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='featured_news_bg_overlay',
            field=models.CharField(choices=[('0', 'Off'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', 'Full')], default='0', help_text='Adjust the opacity of the background image overlay', max_length=50, verbose_name='Overlay Opacity'),
        ),
    ]
