# Generated by Django 3.0.5 on 2020-05-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_auto_20200508_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerfooter',
            name='featured_news_bg_invert',
            field=models.CharField(blank=True, choices=[('', 'Dark'), ('image--light', 'Light')], default='', help_text='Invert the image overlay', max_length=50, null=True, verbose_name='Invert Dark/Light'),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='featured_news_bg_overlay',
            field=models.CharField(blank=True, choices=[('0', 'Off'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', 'Full')], default='0', help_text='Adjust the opacity of the background image overlay', max_length=50, null=True, verbose_name='Overlay Opacity'),
        ),
    ]
