# Generated by Django 3.0.5 on 2020-06-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_auto_20200521_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='header',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
