# Generated by Django 3.0.5 on 2020-08-13 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('app', '0092_auto_20200603_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('destination', models.TextField(blank=True, help_text='When clicked in the navigation, this URL wis where the user will browse to.', null=True, verbose_name='Destination URL')),
                ('hide_in_sitemap', models.BooleanField(default=False, help_text="Don't show this page in the sitemap.", verbose_name='Hide in sitemap')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
