# Generated by Django 3.0.10 on 2020-09-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_auto_20200904_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='credentials',
            field=models.TextField(blank=True),
        ),
    ]
