# Generated by Django 3.0.14 on 2022-03-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_auto_20201112_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultpage',
            name='include_contact_form',
            field=models.BooleanField(default=False, help_text='Attach Contact Form To Bottom of Page', verbose_name='Attach Contact Form To Bottom of Page'),
        ),
    ]
