# Generated by Django 3.0.14 on 2022-03-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_defaultpage_include_contact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='include_contact_form',
            field=models.BooleanField(default=False, help_text='Attach Contact Form To Bottom of Page', verbose_name='Attach Contact Form'),
        ),
    ]
