# Generated by Django 3.0.14 on 2022-03-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_auto_20220304_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpage',
            name='include_contact_form',
            field=models.BooleanField(default=False, help_text='Attach Contact Form To Bottom of Page', verbose_name='Attach Contact Form'),
        ),
    ]
