# Generated by Django 3.0.14 on 2022-04-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('app', '0103_auto_20220407_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinarpage',
            name='document',
        ),
        migrations.RemoveField(
            model_name='webinarpage',
            name='link',
        ),
        migrations.RemoveField(
            model_name='webinarpage',
            name='type',
        ),
        migrations.AlterField(
            model_name='webinarpage',
            name='image',
            field=models.ForeignKey(help_text='Image Dimensions 200x230px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
    ]
