# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_analytics_tag', models.CharField(blank=True, default='', help_text='Enter your GTM code here.', max_length=50, null=True, verbose_name='Tag Manager ID')),
                ('robots_txt', models.TextField(blank=True, default='', help_text='Enter your robots.tx crawler directions here', null=True, verbose_name='Robots.txt')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
