# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20190131_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pwa_use_manifest',
            field=models.BooleanField(default=False, help_text='Check this box if you want to provide a PWA manifest.', verbose_name='Use PWA Manifest'),
        ),
    ]
