# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesettings_pwa_use_manifest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='background_color',
            new_name='pwa_background_color',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='display',
            new_name='pwa_display',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='orientation',
            new_name='pwa_orientation',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='scope',
            new_name='pwa_scope',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='theme_color',
            new_name='pwa_theme_color',
        ),
    ]
