# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_auto_20190131_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='start_url',
            new_name='pwa_start_url',
        ),
    ]
