# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('site_settings', '0008_sitesettings_pwa_icon_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pwa_icon_large',
            field=models.ForeignKey(blank=True, help_text='This icon should be a 512x512 pixel png file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='large_icon', to='wagtailimages.Image', verbose_name='Large Icon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='pwa_icon_small',
            field=models.ForeignKey(blank=True, help_text='This icon should be a 192x192 pixel png file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='small_icon', to='wagtailimages.Image', verbose_name='Small Icon'),
        ),
    ]
