# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_auto_20190131_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='robots_txt',
            field=models.TextField(blank=True, default='User-agent: *\nDisallow: /', help_text='Enter your robots.tx crawler instructions here', null=True, verbose_name='Robots.txt'),
        ),
    ]
