# Generated by Django 2.2.7 on 2019-12-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0012_auto_20191122_1819'),
        ('site_settings', '0012_auto_20191205_2053'),
    ]

    operations = [
    ]
